name: Build Apk

on:
  push:
    branches:
      - main

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build the app
        run: ./gradlew build

      - name: Distribute build to AppCenter
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: grzegorzdziubinski/Patronage
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: Collaborators
          file: app/build/outputs/apk/debug/app-debug.apk
          notifyTesters: true
          debug: true