name: Check pull request

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Build the app
        run: ./gradlew build
        
      - name: Unit tests
        run: ./gradlew test
      
